Update fundamental.py
Previous code caused Error:
'''
TypeError                                 Traceback (most recent call last)
<ipython-input-15-d67443cc025b> in <module>
      1 a = [-1,1,1,-1]
      2 
----> 3 (a < 0).astype(int)

TypeError: '<' not supported between instances of 'list' and 'int'
'''

Also comparator changed so that mapping is (-1 -> 0) and (1 -> 1) instead of (-1 -> 1) and (1 -> 0).